DROP TABLE IF EXISTS user_balance;
DROP TABLE IF EXISTS user_history;
DROP TABLE IF EXISTS user;

CREATE TABLE IF NOT EXISTS user(
    id BIGINT AUTO_INCREMENT,
    PRIMARY KEY(id)
);
CREATE TABLE IF NOT EXISTS user_balance(
    id BIGINT AUTO_INCREMENT,
    user_id BIGINT,
    balance BIGINT,
    CONSTRAINT USER_BALANCE_INSTANCE_EXECUTION_FK FOREIGN KEY (user_id) REFERENCES user(id),
    PRIMARY KEY(id)
);
CREATE TABLE IF NOT EXISTS user_history(
    id BIGINT AUTO_INCREMENT,
    user_id BIGINT,
    CONSTRAINT USER_HISTORY_INSTANCE_EXECUTION_FK FOREIGN KEY (user_id) REFERENCES user(id),
    PRIMARY KEY(id)
);